version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mimico_postgres
    restart: always
    environment:
      POSTGRES_USER: mimico
      POSTGRES_PASSWORD: mimico123
      POSTGRES_DB: mimico_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

